### ISSUE TITLE
service principal metric

### ISSUE THREAD

**Issue by oalimerko** [webdevops/azure-resourcegraph-exporter#1]
Hello,

could  you please give me a hint how to create a metric for listing service principal and his expiry date?

BR
oalimerko

**Comment by mblaschke** [comment]
the `azure-resourcegraph-exporter` only exports information which is available via Azure ResourceGraph API.

what you are looking for is available from the [`azure-resourcemanager-exporter`](https://github.com/webdevops/azure-resourcemanager-exporter), available as `azurerm_graph_app_credential`
