### ISSUE TITLE
Azure Rate limit not expose on subscription level

### ISSUE THREAD

**Issue by jiragrid** [webdevops/azure-resourcegraph-exporter#10]
I got azurerm_rate_limit but still get only tenant level
I've configured subscription id already.
Environment that has been configured.

AZURE_LOCATION:                       southeastasia
SCRAPE_TIME_QUOTA:                    2m
AZURE_TENANT_ID:                      xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
METRIC_AZURERM_API_RATELIMIT_ENABLE:  true
CONFIG:                               /etc/configs/config.yaml
AZURE_SUBSCRIPTION_ID:                xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by mblaschke** [comment]
for subscription level rate limit you have to call the Azure API on subscription level.
The ResourceGraph API is a different API and doesn't work on a specific subscription level, so you cannot get these metrics with this exporter.
