### ISSUE TITLE
Auto lookup of subscriptions fetches only first 1000 subs

### ISSUE THREAD

**Issue by j-sokol** [webdevops/azure-resourcegraph-exporter#3]
When config doesn't have target subscriptions specified (and uses the auto lookup), it fetches only first 1000 subscriptions attached to the Service Principal. 

To load all of them, the code should use ` ListComplete(ctx)` (https://github.com/Azure/azure-sdk-for-go/blob/main/services/subscription/mgmt/2020-09-01/subscription/subscriptions.go#L200) and then iterate over them.

**Comment by mblaschke** [comment]
Fixed when switching to webdevops/go-common
