### ISSUE TITLE
row limit

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-resourcegraph-exporter#5]
Hi all,

the example file contains a warning about the row limit

https://github.com/webdevops/azure-resourcegraph-exporter/blob/450af5cf4de95c9b40f6c3da6077af8166a16d8e/example.azure.yaml#L241

which is 1000 by default. I saw paging is implement in this exporter, it's possible to fetch query answers that extend 1000 resources.

Is the warning in the configuration still mentionable?

**Comment by mblaschke** [comment]
already fixed, notice was already removed
